<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class case_inputRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'name' => 'required|min:2|max:255',
            'tel'  => 'required|numeric|digits:10',
            'sub_problem' => 'required|numeric'
        ];
    }
    public function  messages()
    {
        return[
            'name.required' => 'ท่านยังไม่ได้ระบุชื่อ',
            'tel.required'  => 'ท่านยังไม่ได้ระบุเบอร์มือถือ',
            'tel.numeric'   => 'เบอร์โทรศัพท์ผิดพลาด',
            'tel.digits'    => 'ระบุเบอร์โทรศัพท์มือถือ 10 หลัก',
            'sub_problem.required'    => 'ท่านยังไม่ได้เลือกประเภทปัญหา',
        ];
       // return parent::messages(); // TODO: Change the autogenerated stub
    }
}
